# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=4)),
                ('value', models.CharField(default='0000000000000000', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MipsProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=4)),
                ('opcode', models.CharField(blank=True, max_length=8)),
                ('instruction', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=4)),
                ('value', models.CharField(default='0000000000000000', max_length=16)),
            ],
        ),
    ]
