# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_mipsprogram_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipsprogram',
            name='dest',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='mipsprogram',
            name='src1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='mipsprogram',
            name='src2',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
