# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_auto_20180409_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipsprogram',
            name='cmd',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
