# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_mipsprogram_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipsprogram',
            name='jumpTo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
